title: Pure
author: Twinkle
description: Creating a blog layout using Pure
email: 

avatar: avatar.png

menu:
  archives: /archives
  about: /about

disqus_shortname: 
duoshuo_shortname: saintwinkle

weibo: 
github: 
gplus: 
twitter: 